name: create hello-world container on test
on:
  workflow_dispatch:
    
jobs:
  run_day2_operations on test:
    runs-on: self-hosted
    steps:
      - name: run day2operations on test
        run: |
          ansible-playbook -i test/inventory.ini create_hello-world_container-t.yml
          