name: VM Deployment with terraform and ansible
on:
  pull_request: # runs at pull request
    types:
      - closed
    branches:
      - 'main' # in main branch
    paths:
      - '**.tf'  # runs only when terraform file is changed
jobs:
  install-webserver:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: run terraform Deployment (test)
        run: |
          terraform init
          # check terraform syntax. Deze stap staat hier omdat de provider aanwezig moet zijn (in de init fase)
          terraform validate
          terraform fmt
          terraform plan
          terraform apply -auto-approve
                 
      - name: Run Ansible Playbook day2operations
        run: |
          ansible-playbook -i inventory.ini day2operations.yml
          
      
          
      